# Generated by Django 3.2.3 on 2021-08-12 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_students_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='sid',
        ),
    ]
